accounts/urls.py
from django.urls import path, include
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'), 
]

api/urls.py
from django.urls import path, include
from .views import CocktailList, CocktailDetails, UserList, CocktailCreate
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    # Cocktails CRUD
    path('v1/cocktails/', CocktailList.as_view(), name='cocktail_list'),
    path('v1/cocktails/<int:pk>/', CocktailDetails.as_view(), name='cocktail.details'),
    path('v1/cocktails/create/', CocktailCreate.as_view(), name='cocktail_create'),
    
    # Users List
    path('v1/users/', UserList.as_view(), name="user_list"),

    # Authentication
    path('api-auth/', include('rest_framework.urls')),
    path('v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),

    # Schema/Documentation
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

bar_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # login & logout
    path('api/', include('api.urls')),
    path('', include('cocktails.urls')),
]

cocktails/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(
        'cocktails/',
        include(
            [
                path('list/', views.CocktailsList.as_view(), name='cocktailslist'),
                path('featuredlist/', views.FeaturedCocktailsList.as_view(), name='featuredcocktailslist'),
                path('<int:pk>/details/', views.CocktailsDetail.as_view(), name='cocktailsdetail'),
                path('add/', views.CreateCocktail.as_view(), name='newcocktail'),
                path('<int:pk>/edit', views.UpdateCocktail.as_view(), name='editcocktail'),
                path('<int:pk>/delete', views.DeleteCocktail.as_view(), name='deletecocktail'),
            ]
        ),
    ),
    path('search/', views.SearchResultsListView.as_view(), name='search_results'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CustomUser(AbstractUser):
    name = models.CharField(null=True, blank=True, max_length=100)

api/models.py
from django.db import models

# Create your models here.

cocktails/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class MixedDrinks(models.Model):
    name = models.CharField(max_length=70)
    recipe = models.TextField()
    garnishes = models.TextField(default='No garnish needed.')
    image = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        #return reverse("model_detail", kwargs={"pk": self.pk})
        return reverse("home")


class FeaturedMixedDrinks(models.Model):
    name = models.ForeignKey("MixedDrinks", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name.name
    
    def get_absolute_url(self):
        #return reverse("model_detail", kwargs={"pk": self.pk})
        return reverse("home")

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('name',)


class CustomerUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

cocktails/forms.py
from django import forms

from .models import MixedDrinks


class CreateCocktailForm(forms.ModelForm):
    
    class Meta:
        model = MixedDrinks
        fields = ('name','recipe', )


class UpdateCocktailForm(forms.ModelForm):

    class Meta:
        model = MixedDrinks
        fields = ('name','recipe', 'image')

    

class DeleteCocktailForm(forms.ModelForm):

    class Meta:
        model = MixedDrinks
        fields = ('name','recipe', 'image')

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.edit import FormView
from django.contrib.auth import login
from django.shortcuts import redirect

from .forms import CustomUserCreationForm

# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

api/views.py
from django.shortcuts import render
from rest_framework import generics, permissions
from django.contrib.auth import get_user_model
from rest_framework.response import Response
from rest_framework import status

from cocktails.models import MixedDrinks
from .serializer import CocktailSerializer, UserSerializer


# Create your views here.
class CocktailList(generics.ListAPIView):
    queryset = MixedDrinks.objects.all()
    serializer_class = CocktailSerializer

class CocktailCreate(generics.CreateAPIView):
    permission_classes = (permissions.IsAdminUser,)
    queryset = MixedDrinks.objects.all()
    serializer_class = CocktailSerializer

class UserList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAdminUser,)
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer



class CocktailDetails(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAdminUser,)
    queryset = MixedDrinks.objects.all()
    serializer_class = CocktailSerializer

cocktails/views.py
from typing import Any
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect

from .models import MixedDrinks, FeaturedMixedDrinks
from .forms import CreateCocktailForm, UpdateCocktailForm, DeleteCocktailForm

# Create your views here.
class HomeView(TemplateView):
    template_name = 'cocktails/home.html'


class CocktailsList(ListView):
    model = MixedDrinks
    template_name = 'cocktails/cocktails_list.html'
    

class FeaturedCocktailsList(ListView):
    model = FeaturedMixedDrinks
    template_name = 'cocktails/featured_cocktails_list.html'

class CocktailsDetail(DetailView):
    model = MixedDrinks
    template_name = 'cocktails/cocktails_detail.html'


class CreateCocktail(CreateView):
    model = MixedDrinks
    template_name = 'cocktails/create_cocktail.html'
    form_class = CreateCocktailForm


class UpdateCocktail(UpdateView):
    model = MixedDrinks
    template_name = 'cocktails/edit_cocktail.html'
    form_class = UpdateCocktailForm
    success_url = reverse_lazy('cocktailslist')


class DeleteCocktail(DeleteView):
    model = MixedDrinks
    template_name = 'cocktails/delete_cocktail.html'
    success_url = reverse_lazy('cocktailslist')


class SearchResultsListView(ListView):
    model = MixedDrinks
    template_name = 'cocktails/search_results.html'
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        return MixedDrinks.objects.filter(
            Q(name__icontains=query)
        )

cocktails/templates/cocktails/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cocktails/style.css' %}">
    {% block head %}
    {% endblock head %}
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'home' %}">Cocktails Cabinet</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'featuredcocktailslist' %}">Featured Cocktails</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'cocktailslist' %}">All Cocktails</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
                </ul>
                <form class="d-flex" action="{% url 'search_results' %}" method="get">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" >
                    <br><button class="btn btn-outline-warning" type="submit">Search</button>
                </form>
                {% if user.is_authenticated %}
                
                <ul class="nav" style="padding-top:10px;">
                    <p class="nav-item text-light" style="margin-left: 15px; padding-top:9px;">Hi {{ user }}! </p>
                    <li class="nav-item"><a class="nav-link text-light " href="{% url 'logout' %}">Logout</a></li>
                </ul>
                {% else %}
                    <ul class=" nav auth" style="margin-left:15px;">
                        <li><a class="text-light" href="{% url 'login' %}">Login</a></li>
                        <!--<li><a class="text-light" href="{% url 'signup' %}">/ Signup</a></li>-->
                    </ul>
                {% endif %}
            </div>
        </nav>
    </header>
    
    <main class="flex-grow-1">
        {% block content %}
        {% endblock content %}
    </main>

    <footer class="bg-dark text-light">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2023 Your Company</p>
                </div>
                <div class="col-md-6 text-right">
                    <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
                </div>
            </div>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

cocktails/templates/cocktails/cocktails_detail.html
{% extends 'cocktails/base.html' %}
{% block content %}

{% if user.is_authenticated %}
<div class="container-fluid crudContainer">
    <div class="row">
        <div class="col-2"  style="text-align: right;">
            <h6><a class="crud font-italic text-decoration-none text-dark" href="{% url 'editcocktail' object.pk %}">Edit Cocktail </a></h6>
        </div>
        
        <div class="col-2">
            <h6><a class="crud font-italic text-decoration-none text-dark" href="{% url 'deletecocktail' object.pk %}">Delete Cocktail </a></h6>
        </div>
    </div>
</div>
{% endif%}

    <div class="container   d-flex justify-content-center" style="margin-top:40px;">
        <div class="row bg-white">
            <div class="col">
               <div class="row">
                    <div class="col">
                        <h1 class="text-dark">Cocktail: {{ mixeddrinks.name }} <span class="badge bg-secondary"></span></h1><hr>
                    </div>
               </div>
               <div class="row">
                    <div class="col">
                        <h2 class="text-decoration-underline" style="margin-top:45px;">Ingredients: <span class="badge bg-secondary"></span></h2><br>
                        <h5>{{ mixeddrinks.recipe|linebreaksbr|safe }}<span class="badge bg-secondary"></span></h5>
                    </div>
               </div>
               <div class="row">
                <div class="col">
                    <h2 class="text-decoration-underline" style="margin-top:45px;">Garnishes: <span class="badge bg-secondary"></span></h2><br>
                    <h5>{{ mixeddrinks.garnishes|linebreaksbr|safe }}<span class="badge bg-secondary"></span></h5>
                    </div>
               <div class="row" style="margin-bottom:20px;">
                <div class="col">
                    <h2 class="text-decoration-underline" style="margin-top:45px;">Final Look: <span class="badge bg-secondary"></span></h2><br>
                    <div class="card" style="width:18rem;">
                        <img class="default-image" src="{{ object.image }}" class="card-img-top" alt="..."></img>
                    </div>
                </div>
               </div>
            </div>
        </div>
    </div>

{% endblock content %}


 

cocktails/templates/cocktails/cocktails_list.html
{% extends 'cocktails/base.html' %}
{% block content %}
    <div class="container-fluid" style="margin-top:40px;">
        <div class="row bg-white">
            <div class="col">
                <h1 class="d-flex justify-content-center align-items-center">All Cocktails: <span class="badge bg-secondary"></span></h1>  
                {% for list in mixeddrinks_list  %}
                        <a class="cocktail_ls" style="margin-left:10px;" href="{% url 'cocktailsdetail' list.pk %}">{{ forloop.counter }}. {{ list.name }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

cocktails/templates/cocktails/create_cocktail.html
{% extends 'cocktails/base.html' %}
{% load static %}
{% block content %}
    <h1>Add A New Cocktail:</h1>
    <form method="post" class="my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
{% endblock content %}

cocktails/templates/cocktails/delete_cocktail.html
{% extends 'cocktails/base.html' %}
{% block content %}
    


    <div class="container" style="margin-top:50px;">
        <div class="row">
            <div class="col">
                <h1 style="margin-bottom:20px;">Delete {{ object.name }}?</h1>
                <form method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

cocktails/templates/cocktails/edit_cocktail.html
{% extends 'cocktails/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top:50px;">
        <div class="row">
            <div class="col">
                <h1>Edit Cocktail:</h1>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

cocktails/templates/cocktails/featured_cocktails_list.html
{% extends 'cocktails/base.html' %}
{% block content %}
    <div class="container-fluid" style="margin-top:40px;">
        <div class="row bg-white">
            <div class="col">
                <h1 class="d-flex justify-content-center align-items-center">Featured Cocktails: <span class="badge bg-secondary"></span></h1>  
                {% for list in featuredmixeddrinks_list  %}
                 <a class="cocktail_ls" style="margin-left:10px;" href="{% url 'cocktailsdetail' list.name.pk %}">{{ forloop.counter }}. {{ list.name.name }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

cocktails/templates/cocktails/home.html
{% extends 'cocktails/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'cocktails/style.css' %}">
{% endblock head %}
{% block content %}
  <!--Header--> 
  <div
  id="header"
  class=" text-center bg-image"
  style="background-image: url('https://mybartender.com/wp-content/uploads/2023/06/sweet-cocktails-1024x576.png');height:50vh;"
  >
  <div class="mask">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white">
        <h1 class="mb-3">Welcome to Cocktails Cabinet!</h1>
        <h5 class="mb-4">Design your own cocktails</h5>
        <a
          class="head-btn btn btn-outline-light btn-lg m-2"
          href="{% url 'featuredcocktailslist' %}"
          role="button"
          rel="nofollow"
        >Our Featured Cocktails</a>
      </div>
    </div>
  </div>
  </div>

  <!--Section 1-->
  <section class="steps container-custom">

    <div class="row">
      <div class="col-12 col-sm-6 d-md-flex justify-content-md-center">
        <img src="https://media.timeout.com/images/105619705/1920/1080/image.jpg" class="img-fluid pb-4 steps__section-thumnail" 
        alt="cocktail magic" width="600" height="400" loading="lazy">
      </div>

      <div class="col-12 col-sm-6 align-self-center justify-content-md-center">

        <div class="steps__content-width">
          <span>01</span>
          <h1 class="h2 mb-4">Become A Today Pro!</h1>
          <p class="mb-4">Learn how to make world-class cocktails in the comfort of your own space.</p>
          <a class="text-decoration-none text-info" href="{% url 'cocktailslist' %}">Learn Now <i class="bi bi-arrow-right-short"></i></a>
        </div>

      </div>
    </div>
    
  </section>

  <section class="steps container-custom">

    <div class="row">
      <div class="col-12 col-sm-6 d-md-flex justify-content-md-center order-sm-1">
        <img src="https://cf.ltkcdn.net/cocktails/images/std/252523-800x602r1-friends-making-cocktails.webp" class="img-fluid pb-4 steps__section-thumnail" 
        alt="cocktail magic" width="600" height="400" loading="lazy">
      </div>

      <div class="col-12 col-sm-6 align-self-center justify-content-md-center">

        <div class="steps__content-width">
          <span>02</span>
          <h1 class="h2 mb-4">Impress Your Friends!</h1>
          <p class="mb-4">Create famous cocktails for your friends that taste great!.</p>
          <a class="text-decoration-none text-info" href="{% url 'cocktailslist' %}">Learn Now <i class="bi bi-arrow-right-short"></i></a>
        </div>

      </div>
    </div>
    
  </section>
{% endblock content %}


  <!--
    <div 
    class="master-head"
    style="background-image: url('https://mybartender.com/wp-content/uploads/2023/06/sweet-cocktails-1024x576.png');"
    >
        <div class="color-overlay d-flex justify-content-center align-items-center text-black">
            <h1 class="master-head-text">Welcome to Cabinet Cocktails!</h1>
        </div>
    </div>
  -->


<!--
<div class="container-fluid">
    <div class="row">
      <div class="col-12 p-0">
        <div class="header">
          <img src="https://img.freepik.com/free-photo/fresh-cocktails-with-ice-lemon-lime-fruits-generative-ai_188544-12370.jpg" class="img-fluid" alt="Responsive image">
          <div class="centered-text">
            <h1 class="text-dark bg-white" style="">Welcome To The Cocktails Cabinet!</h1>
            <p>Additional description if needed</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
        <div class="col-12 p-0">
          <p>f</p>
        </div>
      </div>
  </div>
-->






<!--
    <div class="container d-flex justify-content-center  align-items-center">
    <div class="row bg-danger">
        <div class="col bg-light">
            <img src="https://img.freepik.com/free-photo/fresh-cocktails-with-ice-lemon-lime-fruits-generative-ai_188544-12370.jpg" class="img-fluid" alt="Responsive image">
            <h1 class="text-dark bg-white" style="">Welcome To The Cocktails Cabinet!</h1>
        </div>
    </div>
</div>
-->

cocktails/templates/cocktails/search_results.html
{% extends 'cocktails/base.html' %}
{% block title %}Search{% endblock title %}

{% block content %}
    <div class="container-fluid" style="margin-top:40px;">
        <div class="row">
            <div class="col">
                <h1 class="d-flex justify-content-center align-items-center">Search Results</h1>
            </div>
        </div>
        <div class='row'>
            <div class='col'>
                {% for list in mixeddrinks_list  %}
                 <a class="cocktail_ls" href="{% url 'cocktailsdetail' list.pk %}">{{ forloop.counter }}. {{ list.name }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

cocktails/templates/cocktails/test.html
<form method="post" action="">
    {% csrf_token %}
    <button type="submit" name="redirect_button">Click to Redirect</button>
</form>